'use client'

import dynamic from 'next/dynamic'
import type { CardGroup } from '@/lib/designSystemDoc'
import { SystemCards } from '../../../components/SystemCards'

/**
 * Client-only: the vendored bundle destructures a `window` global at module
 * scope, so it cannot be evaluated during prerender. The route stays static;
 * only this subtree waits for the browser.
 */
const Components = dynamic(() => import('./Components'), {
  ssr: false,
  loading: () => <p className="speccard__sub">Loading components…</p>,
})

/**
 * Carries the OC Fellows stylesheet so it is code-split with this system
 * rather than loaded on every design-system route.
 *
 * The import is the whole point of the file: `guide.css` is generated by
 * `scripts/build-guide-css.mjs oc-fellows` and namespaces the bundle's tokens
 * and rules under `.ocfguide`, which is the class the cards are rendered into.
 */
import './guide.css'

export function OcFellowsCards({ groups, title }: { groups: CardGroup[]; title: string }) {
  return (
    <SystemCards
      groups={groups}
      scopeClass="ocfguide"
      title={title}
      live={[{ id: 'components', label: 'Components', node: <Components /> }]}
    />
  )
}
