/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    'case-studies': CaseStudy;
    explorations: Exploration;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    explorations: ExplorationsSelect<false> | ExplorationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Live sites and builds. Ordered by the Order field, lowest first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * The URL segment: /projects/<slug>. Changing it breaks existing links.
   */
  slug: string;
  /**
   * The client or the kind of work — shown under the title.
   */
  category?: string | null;
  /**
   * The live site. Leave empty if it is no longer up.
   */
  url?: string | null;
  /**
   * One paragraph. Shown in full on the project page.
   */
  description: string;
  /**
   * Landscape. Screenshots are letterboxed rather than cropped — see Cover fit.
   */
  cover?: (number | null) | Media;
  /**
   * Photography crops happily. A UI screenshot loses its chrome when it does.
   */
  coverFit?: ('cover' | 'contain') | null;
  /**
   * Lowest first.
   */
  order?: number | null;
  /**
   * Show on the homepage.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Long-form pieces. Everything else is a project or an exploration.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug: string;
  client?: string | null;
  discipline?: string | null;
  /**
   * e.g. 2026
   */
  year?: string | null;
  /**
   * One-paragraph standfirst. Used on the index tile and the detail hero.
   */
  summary: string;
  cover?: (number | null) | Media;
  coverFit?: ('cover' | 'contain') | null;
  /**
   * Lowest first.
   */
  order?: number | null;
  /**
   * Cross-linked at the foot of the piece.
   */
  relatedProject?: (number | null) | Project;
  /**
   * For two pieces that are halves of one story.
   */
  relatedCaseStudy?: (number | null) | CaseStudy;
  blocks?:
    | (
        | {
            heading?: string | null;
            body?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'prose';
          }
        | {
            heading: string;
            note?: string | null;
            items?:
              | {
                  name: string;
                  /**
                   * Any CSS background: a hex, or a gradient.
                   */
                  value: string;
                  note?: string | null;
                  /**
                   * Tick for a pale swatch, so its label is set dark.
                   */
                  onLight?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'swatches';
          }
        | {
            heading: string;
            note?: string | null;
            items?:
              | {
                  role: string;
                  face: string;
                  sample: string;
                  /**
                   * CSS properties for the specimen, e.g. {"fontSize":"48px","letterSpacing":"-0.02em"}. JSON because a specimen is a piece of typesetting, and enumerating every property as a field would be a worse form than the CSS itself.
                   */
                  style?:
                    | {
                        [k: string]: unknown;
                      }
                    | unknown[]
                    | string
                    | number
                    | boolean
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'type';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            heading?: string | null;
            note?: string | null;
            columns?: ('2' | '3') | null;
            items?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Design pieces shown as a gallery. No write-up, just the image.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "explorations".
 */
export interface Exploration {
  id: number;
  title: string;
  /**
   * The URL segment. Titles repeat across a series, so slugs carry a suffix to stay unique.
   */
  slug: string;
  category: 'web' | 'social';
  /**
   * Lowest first.
   */
  order?: number | null;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'explorations';
        value: number | Exploration;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  url?: T;
  description?: T;
  cover?: T;
  coverFit?: T;
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  discipline?: T;
  year?: T;
  summary?: T;
  cover?: T;
  coverFit?: T;
  order?: T;
  relatedProject?: T;
  relatedCaseStudy?: T;
  blocks?:
    | T
    | {
        prose?:
          | T
          | {
              heading?: T;
              body?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        swatches?:
          | T
          | {
              heading?: T;
              note?: T;
              items?:
                | T
                | {
                    name?: T;
                    value?: T;
                    note?: T;
                    onLight?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        type?:
          | T
          | {
              heading?: T;
              note?: T;
              items?:
                | T
                | {
                    role?: T;
                    face?: T;
                    sample?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              heading?: T;
              note?: T;
              columns?: T;
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "explorations_select".
 */
export interface ExplorationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  order?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The homepage copy, in page order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Set on its own line.
   */
  heroNameFirst: string;
  /**
   * The second line, set in the accent treatment.
   */
  heroNameLast: string;
  /**
   * The one line under the name.
   */
  heroTagline: string;
  /**
   * Oversized background word. Two or three words at most.
   */
  heroWatermarkLeft?: string | null;
  heroWatermarkRight?: string | null;
  /**
   * Portrait orientation. Shown above the name.
   */
  heroPortrait?: (number | null) | Media;
  aboutEyebrow?: string | null;
  aboutPortrait?: (number | null) | Media;
  /**
   * The opening statement, set large. One sentence.
   */
  aboutLede: string;
  aboutBody?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Four fit the grid.
   */
  aboutPillars?:
    | {
        title: string;
        copy: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Only real, checkable numbers. A portfolio figure that cannot be substantiated is worse than no figure.
   */
  statsItems?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The paragraph beside the numbers.
   */
  statsStatement?: string | null;
  capabilitiesEyebrow?: string | null;
  capabilitiesGroups?:
    | {
        title: string;
        tags?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  howEyebrow?: string | null;
  /**
   * One line under the heading. Sets up the four steps.
   */
  howLede?: string | null;
  howSteps?:
    | {
        title: string;
        copy: string;
        /**
         * Portrait-ish. Falls back to a placeholder when empty.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  projectsEyebrow?: string | null;
  projectsTitle?: string | null;
  caseStudiesEyebrow?: string | null;
  caseStudiesTitle?: string | null;
  showcaseEyebrow?: string | null;
  showcaseTitle?: string | null;
  contactEyebrow?: string | null;
  contactHeadlineLead?: string | null;
  /**
   * The second half, set in the accent treatment.
   */
  contactHeadlineAccent?: string | null;
  contactCtaLabel?: string | null;
  email?: string | null;
  /**
   * Full URL.
   */
  contactLinkedin?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroNameFirst?: T;
  heroNameLast?: T;
  heroTagline?: T;
  heroWatermarkLeft?: T;
  heroWatermarkRight?: T;
  heroPortrait?: T;
  aboutEyebrow?: T;
  aboutPortrait?: T;
  aboutLede?: T;
  aboutBody?:
    | T
    | {
        text?: T;
        id?: T;
      };
  aboutPillars?:
    | T
    | {
        title?: T;
        copy?: T;
        id?: T;
      };
  statsItems?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  statsStatement?: T;
  capabilitiesEyebrow?: T;
  capabilitiesGroups?:
    | T
    | {
        title?: T;
        tags?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  howEyebrow?: T;
  howLede?: T;
  howSteps?:
    | T
    | {
        title?: T;
        copy?: T;
        image?: T;
        id?: T;
      };
  projectsEyebrow?: T;
  projectsTitle?: T;
  caseStudiesEyebrow?: T;
  caseStudiesTitle?: T;
  showcaseEyebrow?: T;
  showcaseTitle?: T;
  contactEyebrow?: T;
  contactHeadlineLead?: T;
  contactHeadlineAccent?: T;
  contactCtaLabel?: T;
  email?: T;
  contactLinkedin?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}